### ISSUE TITLE
Flatten config file structure

### ISSUE THREAD

**Issue by JulianKarlBauer** [pydykit/pydykit#114]
Up to now, we have a nested config file structure.
For example, the "system"-part within a config file might be encoded like
```yaml
name: visco_pendulum
configuration:
  system:
    class_name: ParticleSystem
    kwargs:
      nbr_spatial_dimensions: 3
      particles:
      - ...
      supports:
      - ...
      springs:
      ...
```

The presence of the nesting level `kwargs` has historic reasons and should be removed, i.e., the above example could be improved to read as
```yaml
name: visco_pendulum
configuration:
  system:
    class_name: ParticleSystem
    nbr_spatial_dimensions: 3
    particles:
    - ...
    supports:
    - ...
    springs:
    ...
```
see code comment in `configuration.py`
```python
# TODO #114: Get rid of nesting in config files to avoid having both ParticleSystem and ParticleSystemKwargs.
#       Switch to something flat, like
# system:
#   class_name: "ParticleSystem"
#   particles: {}
#   springs: {}
```

We could get a further improvement by removing the nesting level `configuration`, leading to a flat config file structure
```yaml
name: visco_pendulum
system:
  class_name: ParticleSystem
  nbr_spatial_dimensions: 3
  particles:
  - ...
  supports:
  - ...
  springs:
  ...
```
see code comment in `configuration.py`
```python
# TODO #114: Consider removing the nesting "configuration"
```
